### PR TITLE
Configuration fixes and information

### PR DESCRIPTION
**Pull request by fievelk**
This PR contains minor changes allowed me to successfully run the project using the following commands:
```zsh
$ npm install
$ npm run build
$ npm run watch
```

I am not a `npm` user, so I just tried to solve the errors that were being raised on my machine with a "trial and error" strategy. Please do feel free to provide any suggestion.

### CODE REVIEW

**Comment by vecna** [comment]
Thanks! I'll integrate the PR ASAP.
sorry for my habit in forgetting "spaces" at the end of the line :D

**Comment by vecna** [comment]
hi @fievelk, I'm importing the PR, just two things:

  * page collaboration is not yet used, do you have in mind how can it looks like? where should be linked from the homepage? how can effectively engage collaborators ?
  * I left many time spaces ad the end of the line, this would contribute to commit. do you have to suggest a tool that automatically can strip them off?

thanks

**Comment by fievelk** [comment]
@vecna Thank you for merging the PR.
I just use Sublime Text for  coding. It automatically strips whitespaces at the end of lines whenever a file gets saved. If you want I can disable this behaviour in my next commits, so that we won't have too many different lines. 

I still have to think about the collaboration page. It could probably be a good idea to discuss about it on the mailing list.

**Comment by vecna** [comment]
The collaboration page is not yet published, and the collaboration will be gradual

**Pull request merged**
